[0m17:26:35.905795 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000294E50F2610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000294E5D03BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000294E5D03EE0>]}


============================== 17:26:35.909795 | bf72bead-8b1f-45d5-aa24-400788075a4e ==============================
[0m17:26:35.909795 [info ] [MainThread]: Running with dbt=1.7.0-a1
[0m17:26:35.911795 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\oluwaloseyi.sekoni\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init data2bots_transformation', 'send_anonymous_usage_stats': 'True'}
[0m17:26:35.926000 [debug] [MainThread]: Starter project path: c:\users\oluwaloseyi.sekoni\appdata\local\programs\python\python38\lib\site-packages\dbt\include\starter_project
[0m17:26:36.009066 [info ] [MainThread]: 
Your new dbt project "data2bots_transformation" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:26:36.010904 [info ] [MainThread]: Setting up your profile.
[0m17:26:41.316240 [debug] [MainThread]: Command `dbt init` succeeded at 17:26:41.316240 after 5.42 seconds
[0m17:26:41.317224 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000294E50F2610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000294E5620610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000294E7638E20>]}
[0m17:26:41.317224 [debug] [MainThread]: Flushing usage events
[0m22:51:19.249290 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7965406A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D79715A670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D79715A640>]}


============================== 22:51:19.257592 | b471d22b-cecf-4a19-903e-1609c480de2d ==============================
[0m22:51:19.257592 [info ] [MainThread]: Running with dbt=1.7.0-a1
[0m22:51:19.258600 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\oluwaloseyi.sekoni\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m22:51:19.259593 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\oluwaloseyi.sekoni\Desktop\demo_pipelines\data2bots_assessment\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:51:19.260592 [debug] [MainThread]: Command `dbt run` failed at 22:51:19.260592 after 0.03 seconds
[0m22:51:19.261622 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7965406A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D797169A60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D797169BB0>]}
[0m22:51:19.261622 [debug] [MainThread]: Flushing usage events
[0m22:52:20.034147 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022B22F406A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022B23B5D640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022B23B5D6D0>]}


============================== 22:52:20.034147 | 3e6f3d5f-dd64-40a6-ad02-53db820a3b32 ==============================
[0m22:52:20.034147 [info ] [MainThread]: Running with dbt=1.7.0-a1
[0m22:52:20.034147 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\oluwaloseyi.sekoni\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:52:20.034147 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\oluwaloseyi.sekoni\Desktop\demo_pipelines\data2bots_assessment\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:52:20.045205 [debug] [MainThread]: Command `dbt run` failed at 22:52:20.045205 after 0.02 seconds
[0m22:52:20.045205 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022B22F406A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022B23B61A60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022B23B61BB0>]}
[0m22:52:20.046205 [debug] [MainThread]: Flushing usage events
[0m22:52:32.690790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E033E916D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E034AA5FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E034AA5F40>]}


============================== 22:52:32.695705 | 858d95db-4b79-4b9a-bde4-7af3de2426b5 ==============================
[0m22:52:32.695705 [info ] [MainThread]: Running with dbt=1.7.0-a1
[0m22:52:32.696688 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\oluwaloseyi.sekoni\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m22:52:32.697685 [info ] [MainThread]: dbt version: 1.7.0-a1
[0m22:52:32.698685 [info ] [MainThread]: python version: 3.8.0
[0m22:52:32.698685 [info ] [MainThread]: python path: c:\users\oluwaloseyi.sekoni\appdata\local\programs\python\python38\python.exe
[0m22:52:32.699687 [info ] [MainThread]: os info: Windows-10-10.0.19041-SP0
[0m22:52:32.862417 [info ] [MainThread]: Using profiles dir at C:\Users\oluwaloseyi.sekoni\.dbt
[0m22:52:32.863419 [info ] [MainThread]: Using profiles.yml file at C:\Users\oluwaloseyi.sekoni\.dbt\profiles.yml
[0m22:52:32.863419 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\oluwaloseyi.sekoni\Desktop\demo_pipelines\data2bots_assessment\dbt_project.yml
[0m22:52:32.864418 [info ] [MainThread]: Configuration:
[0m22:52:32.865419 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m22:52:32.865419 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m22:52:32.866419 [info ] [MainThread]: Required dependencies:
[0m22:52:32.867418 [debug] [MainThread]: Executing "git --help"
[0m22:52:32.983168 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m22:52:32.983168 [debug] [MainThread]: STDERR: "b''"
[0m22:52:32.983168 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m22:52:32.984464 [info ] [MainThread]: Connection test skipped since no profile was found
[0m22:52:32.985471 [info ] [MainThread]: [31m2 checks failed:[0m
[0m22:52:32.985471 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "data2bots_transformation", target "dev" invalid: ['dbname'] is not of type 'string'


[0m22:52:32.986698 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\oluwaloseyi.sekoni\Desktop\demo_pipelines\data2bots_assessment\dbt_project.yml> not found

[0m22:52:32.988708 [debug] [MainThread]: Command `dbt debug` failed at 22:52:32.988708 after 0.31 seconds
[0m22:52:32.988708 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E033E916D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E034ACAA00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E034ACA250>]}
[0m22:52:32.989708 [debug] [MainThread]: Flushing usage events
